# Generated by Django 5.0.3 on 2024-03-31 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_booking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Order',
        ),
    ]
