# Generated by Django 5.0.3 on 2024-03-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_rename_booking_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=100)),
                ('dropoff_location', models.CharField(max_length=100)),
                ('pickup_date', models.DateField()),
                ('dropoff_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
